# Generated by Django 3.1.7 on 2021-03-28 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20210327_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='sobreno',
            new_name='sobrenome',
        ),
    ]
